.github/workflows/2wr-app.yaml
2wr-app/package-lock.json
az/create-frontend-resources.sh
az/deploy-frontend.sh

Deployment script and initial github actions workflow for frontend app.
Waiting on resolution of issue with Azure Subscription that is blocking creation of the CDN profile. In the meantime, app can be found at https://2wrdevwebstorage.z19.web.core.windows.net/
We will also need to configure Azure Credentials for the automated deployments as per https://github.com/marketplace/actions/azure-cli-action#configure-azure-credentials-as-github-secret. Once that is completed, we can comment out the bottom 1/2 of the 2wr-app.yaml workflow and any commits to be automatically deployed to the development environment.

Front end deployments

---

2wr-app/src/api/emergency-kit-api.js
2wr-app/src/components/prepare/emergency-kits/emergency-kit-create.vue
2wr-app/src/components/prepare/emergency-kits/emergency-kit-list.vue
2wr-app/src/router/index.js
2wr-app/src/store/modules/prepare/emergency-kits/emergency-kit-store.js
2wr-app/src/views/prepare/emergency-kits/emergency-kit-create.vue
api/OidcApiAuthorization/Abstractions/IJwtSecurityTokenHandlerWrapper.cs
api/OidcApiAuthorization/JwtSecurityTokenHandlerWrapper.cs
api/OidcApiAuthorization/Models/ApiAuthorizationResult.cs
api/OidcApiAuthorization/OidcApiAuthorizationService.cs
api/TwoWeeksReady/EmergencyKits/EmergencyKit.cs
api/TwoWeeksReady/EmergencyKits/EmergencyKitsApi.cs

Note that this does not represent the actually structure of what an emergency kit should look like. The intention of this PR is to demonstrate how we would access the current user's profile and scope data based on the user's unique ID.

Get user info when validating acces token

---

2wr-app/src/auth/index.js
2wr-app/src/router/index.js

Resolves #22 
I would like to also get this to put the user back to the path they started out at but couldn't quite get that working today. I will try to tackle that tomorrow.

Redirect to login screen if user is not authenticated

---

2wr-app/src/App.vue
2wr-app/src/components/prepare/prepare-landing.vue

Display a banner warning the user that they are using the development version of the app

---

2wr-app/.env-sample
2wr-app/.gitignore
2wr-app/package-lock.json
2wr-app/src/App.vue
2wr-app/src/api/emergency-kit-api.js
2wr-app/src/components/prepare/emergency-kits/emergency-kit-create.vue
2wr-app/src/components/prepare/emergency-kits/emergency-kit-list.vue
2wr-app/src/store/modules/prepare/emergency-kits/emergency-kit-store.js

- Removed some bad juju from the App.vue
- Completed the Create Emergency Kit interface. It allows choosing:
- Name
- Color
- Material icon
- Modified Emergency Kit listing to display the icon associated with the kit

Emergency Kits UI implementation

---

2wr-app/src/components/prepare/emergency-kits/emergency-kit-create.vue
api/README.md
api/api.code-workspace
api/api.sln

Ability to add/edit kit items when creating a kit

---

api/TwoWeeksReady/EmergencyKits/BaseKitsApi.cs

Create API for base kits

---

2wr-app/src/api/hazard-hunt-api.js
2wr-app/src/api/hazard-info-api.js
2wr-app/src/components/prepare/hazards/hazard-hunt-list.vue
2wr-app/src/components/prepare/hazards/hazard-info-list.vue
2wr-app/src/components/prepare/prepare-landing.vue
2wr-app/src/router/index.js
2wr-app/src/store/index.js
2wr-app/src/store/modules/prepare/hazards/hazard-hunt-store.js
2wr-app/src/store/modules/prepare/hazards/hazard-info-store.js
2wr-app/src/views/prepare/hazards/hazard-hunt-list-view.vue
2wr-app/src/views/prepare/hazards/hazard-info-list-view.vue

This is an initial implementation. It will need more work after there is some data to display. I tested it with manually entered data into my local Cosmos DB server.

Preliminary Hazard Hunt/Info UI #30

---

.vscode/launch.json
.vscode/tasks.json
2wr-app/jsconfig.json
2wr-app/package-lock.json
2wr-app/package.json
2wr-app/src/api/family-plans-api.js
2wr-app/src/components/address-editor.vue
2wr-app/src/components/prepare/emergency-kits/emergency-kit-list.vue
2wr-app/src/components/prepare/prepare-landing.vue
2wr-app/src/functions/goBack.js
2wr-app/src/main.js
2wr-app/src/router/index.js
2wr-app/src/store/index.js
2wr-app/src/store/modules/prepare/family-plans/index.js
2wr-app/src/views/prepare/family-plans/create.vue
2wr-app/src/views/prepare/family-plans/landing.vue
2wr-app/src/views/prepare/family-plans/view.vue
TwoWeeksReady.Common/FamilyPlans/Address.cs
TwoWeeksReady.Common/FamilyPlans/Contact.cs
TwoWeeksReady.Common/FamilyPlans/FamilyPlan.cs
TwoWeeksReady.Common/FamilyPlans/Person.cs
TwoWeeksReady.Common/FamilyPlans/Pet.cs
TwoWeeksReady.Common/FamilyPlans/RouteLocation.cs
TwoWeeksReady.Common/FamilyPlans/WalkThroughStep.cs
api/TwoWeeksReady/FamilyPlans/FamilyPlansApi.cs
api/TwoWeeksReady/host.json

First pass at beginning screens of the Family Plans. Create and view should work.

First start of Family Plans

---

2wr-app/package-lock.json
2wr-app/package.json
2wr-app/src/api/family-plans-api.js
2wr-app/src/components/common/EditableTextBlock.vue
2wr-app/src/components/models/family-plans/Address.js
2wr-app/src/components/models/family-plans/FamilyPlan.js
2wr-app/src/components/prepare/family-plans/address.vue
2wr-app/src/components/prepare/family-plans/family-plans-list.vue
2wr-app/src/components/prepare/family-plans/family-plans-view.vue
2wr-app/src/functions/setFocusVuetify.js
2wr-app/src/router/index.js
2wr-app/src/store/index.js
2wr-app/src/store/modules/prepare/family-plans/index.js
2wr-app/src/views/prepare/family-plans/landing.vue
2wr-app/src/views/prepare/family-plans/view.vue
api/TwoWeeksReady/FamilyPlans/FamilyPlansApi.cs

Should allow you to view and edit plans (first page only).

Create Working Plan View

---

2wr-app/src/api/emergency-kit-api.js
2wr-app/src/components/prepare/emergency-kits/emergency-kit-create.vue
2wr-app/src/components/prepare/emergency-kits/emergency-kit-edit.vue
2wr-app/src/components/prepare/emergency-kits/emergency-kit-list.vue
2wr-app/src/router/index.js
2wr-app/src/store/modules/prepare/emergency-kits/emergency-kit-store.js
2wr-app/src/views/prepare/emergency-kits/emergency-kit-edit.vue
api/TwoWeeksReady/EmergencyKits/EmergencyKitsApi.cs

Co-authored-by: Simon Timms <stimms@gmail.com>
Co-authored-by: James Chambers <MisterJames@users.noreply.github.com>

Basic View / Edit Emergency Kit Functionality

---

2wr-app/src/components/prepare/emergency-kits/emergency-kit-create.vue
2wr-app/src/components/prepare/emergency-kits/emergency-kit-edit.vue
2wr-app/src/rules/index.js

#56 
1. Added "Required" validation for Kit Name, Icon, Kit Item Name in both Create and Edit forms.
2. Added max length validator for kit name and kit item name in both Create and Edit forms. I chose 120 but if there is a recommendation on the value please suggest.

Emergency kit Create and Edit forms validation

---

tools/CosmosEmulator/CosmosInitializer.cs

- Fix partition key for emergencykits collection
- Added basekits collection

Improvements to Cosmos Initializer

---

2wr-app/src/store/modules/prepare/emergency-kits/emergency-kit-store.js

Enable loading icon for emergency kit list page

---

admin/TwoWeeksReady.Admin/App.razor
admin/TwoWeeksReady.Admin/Pages/HazardHunts/Details.razor
admin/TwoWeeksReady.Admin/Pages/HazardHunts/List.razor
admin/TwoWeeksReady.Admin/Pages/HazardInfos/Details.razor
admin/TwoWeeksReady.Admin/Pages/HazardInfos/List.razor
admin/TwoWeeksReady.Admin/Pages/Kits/Details.razor
admin/TwoWeeksReady.Admin/Pages/Kits/List.razor
admin/TwoWeeksReady.Admin/Pages/Login.cshtml
admin/TwoWeeksReady.Admin/Pages/Login.cshtml.cs
admin/TwoWeeksReady.Admin/Pages/Logout.cshtml
admin/TwoWeeksReady.Admin/Pages/Logout.cshtml.cs
admin/TwoWeeksReady.Admin/Pages/_Host.cshtml
admin/TwoWeeksReady.Admin/Security/TokenProvider.cs
admin/TwoWeeksReady.Admin/Shared/AccessControl.razor
admin/TwoWeeksReady.Admin/Shared/MainLayout.razor
admin/TwoWeeksReady.Admin/Startup.cs
admin/TwoWeeksReady.Admin/TwoWeeksReady.Admin.csproj
admin/TwoWeeksReady.Admin/appsettings.Development.json
admin/TwoWeeksReady.Admin/appsettings.json

#66  This pull request enables authentication and authorization for admin app.
For authentication and authorization to work, follow below steps.
1. Update `auth0` section settings in `appsettings.Development.json` file in "admin" project.
2. Role name "admin" is used to access Base Kits, Hazard Info, Hazard Hut pages. In Auth0 account, create a role with name admin in "User Management" --> "Roles" and assign the role to a user.
3. In Auth0 account, add an empty rule in "Auth Pipeline" --> "Rules" --> Create new rule and add the below javascript code.
``` javascript
function (user, context, callback) {
const namespace = 'https://schemas.2wradmin.com';
const assignedRoles = (context.authorization || {}).roles;
let idTokenClaims = context.idToken || {};
idTokenClaims[`${namespace}/roles`] = …
```

Admin application - Implement Auth0 authentication

---

README.md

added links to the landing pages of each project so developers can find setup instructions. Closes issue #78

Add project README.md links to the main landing page

---

admin/TwoWeeksReady.Admin/App.razor
admin/TwoWeeksReady.Admin/Data/FunctionsRepository.cs
admin/TwoWeeksReady.Admin/Pages/_Host.cshtml
admin/TwoWeeksReady.Admin/Startup.cs

fixed issue #88 - thanks @dpaquette for the assist :D

added the ability to obtain the access token for api calls.

---

2wr-app/package-lock.json
2wr-app/package.json
2wr-app/playwright.config.js
2wr-app/tests/welcome.spec.js

Related to issue: #98 
Related to issue: #93

Adding basic page load test and accessibility test for welcome page

---

2wr-app/package.json
2wr-app/src/App.vue
2wr-app/src/components/welcome/welcome-landing.vue
2wr-app/src/plugins/vuetify.js

Resolve welcome page a11y violations

---

.github/workflows/2wr-app.yaml
2wr-app/.gitignore
2wr-app/playwright.config.js
2wr-app/tests/global-setup.js
2wr-app/tests/hazard-info.spec.js
2wr-app/tests/welcome.spec.js
api/.vscode/tasks.json

Uses playwright network interception to return mock data for the harzard info list and details page

E2E Hazard Info tests

---

.github/workflows/2wr-app.yaml
.github/workflows/admin.yaml
.github/workflows/api.yaml

Remove references to credential secrets and replace with OIDC based login.
https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure

Move to use OIDC instead of credentials for Azure login
